sleep 5
echo 'RunA'
nohup TnPUtils/skimTree /eos/cms/store/group/phys_muon/TagAndProbe/Run2018/102X/TnPTreeZ_17Sep2018_SingleMuon_Run2018Av2_GoldenJSON.root /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmed_20_RunA2018.root -r "all" -k "pt abseta dB dzPV eta mass pair_newTuneP_mass pair_newTuneP_probe_pt pair_probeMultiplicity pair_deltaR run IsoMu24 IsoTkMu24 Mu50 fixedGridRhoFastjetCentralNeutral miniIsoCharged miniIsoNeutrals miniIsoPhotons combRelIsoPF04dBeta CutBasedIdTight CutBasedIdMedium CutBasedIdLoose tag_nVertices" -c "((pt > 20 || pair_newTuneP_probe_pt > 20) && mass > 69.5 && mass < 130.1 && tag_combRelIsoPF04dBeta < 0.2 && tag_combRelIsoPF04dBeta > -0.5 && tag_pt > 30 && tag_IsoMu27 == 1 && abseta < 2.401 && pair_probeMultiplicity == 1)" > /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmer18A.log 2>&1 &
sleep 5
echo 'RunB'
nohup TnPUtils/skimTree /eos/cms/store/group/phys_muon/TagAndProbe/Run2018/102X/TnPTreeZ_17Sep2018_SingleMuon_Run2018Bv1_GoldenJSON.root /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmed_20_RunB2018.root -r "all" -k "pt abseta dB dzPV eta mass pair_newTuneP_mass pair_newTuneP_probe_pt pair_probeMultiplicity pair_deltaR run IsoMu24 IsoTkMu24 Mu50 fixedGridRhoFastjetCentralNeutral miniIsoCharged miniIsoNeutrals miniIsoPhotons combRelIsoPF04dBeta CutBasedIdTight CutBasedIdMedium CutBasedIdLoose tag_nVertices" -c "((pt > 20 || pair_newTuneP_probe_pt > 20) && mass > 69.5 && mass < 130.1 && tag_combRelIsoPF04dBeta < 0.2 && tag_combRelIsoPF04dBeta > -0.5 && tag_pt > 30 && tag_IsoMu27 == 1 && abseta < 2.401 && pair_probeMultiplicity == 1)" > /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmer18B.log 2>&1 &
sleep 5
echo 'RunC'
nohup TnPUtils/skimTree /eos/cms/store/group/phys_muon/TagAndProbe/Run2018/102X/TnPTreeZ_17Sep2018_SingleMuon_Run2018Cv1_GoldenJSON.root /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmed_20_RunC2018.root -r "all" -k "pt abseta dB dzPV eta mass pair_newTuneP_mass pair_newTuneP_probe_pt pair_probeMultiplicity pair_deltaR run IsoMu24 IsoTkMu24 Mu50 fixedGridRhoFastjetCentralNeutral miniIsoCharged miniIsoNeutrals miniIsoPhotons combRelIsoPF04dBeta CutBasedIdTight CutBasedIdMedium CutBasedIdLoose tag_nVertices" -c "((pt > 20 || pair_newTuneP_probe_pt > 20) && mass > 69.5 && mass < 130.1 && tag_combRelIsoPF04dBeta < 0.2 && tag_combRelIsoPF04dBeta > -0.5 && tag_pt > 30 && tag_IsoMu27 == 1 && abseta < 2.401 && pair_probeMultiplicity == 1)" > /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmer18C.log 2>&1 &
sleep 5
echo 'RunD'
nohup TnPUtils/skimTree /eos/cms/store/group/phys_muon/TagAndProbe/Run2018/102X/TnPTreeZ_SingleMuon_Run2018Dv2_GoldenJSON.root /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmed_20_RunD2018.root -r "all" -k "pt abseta dB dzPV eta mass pair_newTuneP_mass pair_newTuneP_probe_pt pair_probeMultiplicity pair_deltaR run IsoMu24 IsoTkMu24 Mu50 fixedGridRhoFastjetCentralNeutral miniIsoCharged miniIsoNeutrals miniIsoPhotons combRelIsoPF04dBeta CutBasedIdTight CutBasedIdMedium CutBasedIdLoose tag_nVertices" -c "((pt > 20 || pair_newTuneP_probe_pt > 20) && mass > 69.5 && mass < 130.1 && tag_combRelIsoPF04dBeta < 0.2 && tag_combRelIsoPF04dBeta > -0.5 && tag_pt > 30 && tag_IsoMu27 == 1 && abseta < 2.401 && pair_probeMultiplicity == 1)" > /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmer18D.log 2>&1 &

sleep 5
echo 'DYTree'
nohup TnPUtils/skimTree /eos/user/w/wiwong/TagAndProbe/add_PUweight/TnPTree_DY2018_weighted.root /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmed_20_DY2018.root -r "all" -k "pt abseta dB dzPV eta mass pair_newTuneP_mass pair_newTuneP_probe_pt pair_probeMultiplicity pair_deltaR run IsoMu24 IsoTkMu24 Mu50 fixedGridRhoFastjetCentralNeutral miniIsoCharged miniIsoNeutrals miniIsoPhotons combRelIsoPF04dBeta CutBasedIdTight CutBasedIdMedium CutBasedIdLoose tag_nVertices weight" -c "((pt > 20 || pair_newTuneP_probe_pt > 20) && mass > 69.5 && mass < 130.1 && tag_combRelIsoPF04dBeta < 0.2 && tag_combRelIsoPF04dBeta > -0.5 && tag_pt > 30 && tag_IsoMu27 == 1 && abseta < 2.401 && pair_probeMultiplicity == 1)" > /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmer18DY.log 2>&1 &
